# In the development configuration exposes some ports to the host,
# mounts our code as a volume, and builds the web image.
version: "3.7"

services:
  lumen_nginx:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: nginx
    ports:
      - 8083:80
    depends_on:
      - lumen_php
    environment:
      WAIT_HOSTS: lumen_php:9000
    volumes:
      - ./src/public:/var/www/html/public

  lumen_php:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: php
    env_file: .env
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
      WAIT_HOSTS: lumen_db:3306
    depends_on:
      - lumen_db
    command: sh -c "composer install && php-fpm"

  lumen_db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=domain
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - lumen-db:/var/lib/mysql
      - ./transfer:/docker-entrypoint-initdb.d:delegated

volumes:
  lumen-db:
