apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: myapp-staging-
commonLabels:
  app: myapp
bases:
  - ../../base/apps
  - ../../base/db
patchesStrategicMerge:
  - backend/overlays.yaml
  - mysql/overlays.yaml

configMapGenerator:
  - name: public-overlays
    literals:
      - APP_NAME="App Name"
